### ISSUE TITLE
Soy esbva, agregame por esbvaGames

### ISSUE THREAD

**Issue by esbvaGames** [IndieDevEs/TheLegendOfHero#11]
Agregame por esbvaGames, el fork, no se puede ni cambiar el readme, ponele automerge, de archivos distintos de la extensión *.gd,  para que los haga automáticamente dejando el ultimo, sin conflictos !!!
Saludos !!!

**Comment by DeybisMelendez** [comment]
Hola esbva, lo siento por la tardanza, https://github.com/IndieDevEs/TheLegendOfHero/invitations
