### ISSUE TITLE
Crear un asset genérico de pruebas para crear escenarios de pruebas.

### ISSUE THREAD

**Issue by DeybisMelendez** [IndieDevEs/TheLegendOfHero#2]
Crear la directorio /tilesets/temp/ y colocarlo ahí.

**Comment by TKFjbn** [comment]
![Dungeon-Tileset-Test-0](https://user-images.githubusercontent.com/39811151/73699600-008c8e80-46c3-11ea-840f-e395d89348f7.png)

**Comment by DeybisMelendez** [comment]
Me parece bien ese asset para comenzar, ya eligieron la paleta de colores que usaremos? @TaJL @TKFjbn
